[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true
size = 11.0

[font.bold]
family = "Pitagon Sans Mono"
style = "SemiBold"

[font.bold_italic]
family = "Pitagon Sans Mono"
style = "SemiBold"

[font.italic]
family = "Monaspace Radon"
style = "Italic"

[font.normal]
family = "Cartograph CF"
style = "Regular"

[font.offset]
x = 1
y = 0

