local opts = {
    autoindent = true,
    autowrite = true,
    background = "dark",
    backup = false,
    breakindent = true,
    clipboard = "unnamed",
    cmdheight = 1,
    conceallevel = 0,
    completeopt = { "menuone", "noinsert", "noselect", "preview"},
    confirm = true,
    cursorline = true,
    equalalways = true,
    expandtab = true,
    fileencoding = "utf-8",
    fillchars = { eob = " " },
    foldenable = true,
    foldmethod = 'marker',
    hidden = true,
    history = 150,
    hlsearch = true,
    incsearch = true,
    ignorecase = true,
    infercase = true,
    laststatus = 3,
    linebreak = true,
    list = true,
    matchpairs = "(:),{:},[:],<:>",
    mouse = "a",
    mousefocus = true,
    number = true,
    preserveindent = true,
    pumblend = 10,
    pumheight = 10,
    relativenumber = true,
    ruler = false,
    scrolloff = 8,
    shiftwidth = 4,
    showtabline = 4,
    showcmd = false,
    sidescrolloff = 8,
    signcolumn = "yes",
    smartcase = true,
    splitright = true,
    swapfile = false,
    tabstop = 4,
    termguicolors = true,
    timeoutlen = 350,
    undofile = true,
}

for opt, value in pairs(opts) do
    vim.opt[opt] = value
end
