#!/bin/bash

get_layout_icon() {
    local current_desktop
    local layouts
    local layout_array
    local layout_icon
    local temp

    # Get workspace layouts
    layouts=$(dkcmd status type=full num=1 | awk '/^workspaces:/ {sub(/^workspaces: /, ""); gsub(/(*)?[0-9]*:\w*:/, ""); print}')

    # Create array
    read -ra layout_array <<< "$layouts"

    temp=$(awk '/^workspaces:/ {sub(/^workspaces: /, ""); gsub(/:\w*/, ""); print }' <(dkcmd status type=full num=1) | grep -oE '\*\S+' | awk -F '*' '{print $2}')

    # Subtract 1 from temp to get the array index
    local tempi=$((temp - 1))

    # Get current desktop
    current_desktop=$tempi

    # Set variable for the current layout icon
    layout_icon=""

    # Set the current layout icon based on the layout of the current desktop
    case ${layout_array[$current_desktop]} in
        grid)   layout_icon="  " ;;
        tile)   layout_icon="  " ;;
        mono)   layout_icon="  " ;;
        dwindle)layout_icon="  " ;;
        *)      layout_icon="" ;;
    esac

    # Return the layout icon
    echo "$layout_icon"
}


while :; do
    sleep 0.2
    get_layout_icon 
done
