#!/bin/bash

status=$(nmcli g | grep -oE "disconnected")
essid=$(nmcli c | grep wlp0s20f3 | awk '{print ($1)}')
strength=$(nmcli -f ACTIVE,SIGNAL dev wifi | egrep '^yes' | awk '{print $2}')

if [ $status ] ; then
    icon="󰤮"
    text=""
    col="#575268"

else
    if [ "$strength" -ge 90 ]; then
        icon="󰤨"
    elif [ "$strength" -ge 75 ]; then
        icon="󰤥"
    elif [ "$strength" -ge 50 ]; then
        icon="󰤢"
    elif [ "$strength" -ge 20 ]; then
        icon="󰤟"
    else
        icon="󰤯"
    fi

    text="${essid}"
    #col="#a1bdce"
fi

if [[ "$1" == "--COL" ]]; then
    echo $col
elif [[ "$1" == "--ESSID" ]]; then
    echo $text
elif [[ "$1" == "--ICON" ]]; then
    echo $icon
fi
