#!/bin/sh

# determine where to place the log file
logfile="$HOME/.dkrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/dkrc.log"
: > "$logfile"

# Startup

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &
fi

# adjust border widths based on the DPI of the monitor
px=$(xrandr | grep ' connected' | tail -n1 | grep -o '[0-9]\+x[0-9]\+' | cut -d'x' -f2)
mm=$(xrandr | grep ' connected' | tail -n1 | grep -o '[0-9]\+x[0-9]\+' | cut -d'x' -f1)

dpiF=$(echo "scale=2; $px / $mm * 25" | bc)

dpi="${dpiF%.*}"

dpi=$(( dpi * 10))

if [ $dpi -ge 140 ]; then
	border_width=4
    gap=10
elif [ $dpi -ge 120 ]; then
	border_width=4
    gap=8
else
	border_width=2
    gap=5
fi

xrandr --dpi $dpi &

feh --no-fehbg --bg-scale "$HOME/.config/dk/wallpapers/cli.jpg" &

if hash compfy >/dev/null 2>&1; then
	pkill compfy
    compfy --config "$HOME/.config/dk/compfy.conf" -b &
fi


{

# WorkSpace


dkcmd set numws=6

dkcmd set ws=_ apply gap="$gap" msplit=0.5 ssplit=0.5

dkcmd set ws=1 name="I" layout=grid 
dkcmd set ws=2 name="II" layout=mono
dkcmd set ws=3 name="III"
dkcmd set ws=4 name="IV"
dkcmd set ws=5 name="V"
dkcmd set ws=6 name="VI"

# Settings

# focus windows when receiving activation and enable focus-follows-mouse
dkcmd set focus_open=true focus_urgent=true focus_mouse=true

# place clients at the tail and ignore size hints on tiled windows
dkcmd set tile_tohead=0 tile_hints=false

# minimum width/height for resizing, and minimum allowed on-screen when moving
dkcmd set win_minwh=50 win_minxy=10

# disable gaps and borders in single window layouts
dkcmd set smart_gap=false smart_border=true

# define mouse mod and move/resize buttons
dkcmd set mouse mod=alt move=button1 resize=button3

# obey motif border hints on windows that draw their own (steam, easyeffects, etc.)
dkcmd set obey_motif=true

# Set the border width and colour of unfocused windows
dkcmd set border width=$border_width colour focus='#33AAFF' unfocus='#B4B8BD' urgent='#ee5555'

# Rules

dkcmd rule class="^Brave-browser$" ws=2
dkcmd rule class="^discord$" ws=3

} >> "$logfile" 2>&1 # append responses

if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"; print}' "$logfile")"
	exit 1
fi
exit 0
