#!/bin/sh

# determine where to place the log file
logfile="$HOME/.dkrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/dkrc.log"
: > "$logfile"


# Startup

# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/dk/sxhkdrc" &
fi

# adjust border widths based on the DPI of the monitor
px=$(xrandr | grep ' connected' | tail -n1 | grep -o '[0-9]\+x[0-9]\+' | cut -d'x' -f2)
mm=$(xrandr | grep ' connected' | tail -n1 | grep -o '[0-9]\+x[0-9]\+' | cut -d'x' -f1)

dpiF=$(echo "scale=2; $px / $mm * 25" | bc)

dpi="${dpiF%.*}"

dpi=$(( dpi * 10))

if [ $dpi -ge 140 ]; then
	border_width=4
	border_outer_width=3
elif [ $dpi -ge 120 ]; then
	border_width=4
	border_outer_width=2
else
	border_width=2
	border_outer_width=1
fi

xrandr -s 1360x768 &

feh --no-fehbg --bg-scale --randomize "$HOME/.config/dk/wallpapers" &

if hash polybar >/dev/null 2>&1; then
	pkill polybar
    $HOME/.config/polybar/launch.sh &
fi

if pgrep -x "picom" > /dev/null; then
	killall picom
fi

picom --config ~/.config/dk/picom.conf &

{
# Workspace 

dkcmd set numws=6

dkcmd set ws=1 name="I" layout=grid gap=5
dkcmd set ws=2 name="II"
dkcmd set ws=3 name="III"
dkcmd set ws=4 name="IV"
dkcmd set ws=5 name="V"
dkcmd set ws=6 name="VI"

# General

dkcmd set focus_open=true focus_mouse=true

dkcmd set tilet-head=0 tile_hints=false

dkcmd set win_minwh=50 win_minxy=10

dkcmd set smart_gap=false smart_border=true

dkcmd set mouse mod=alt move=button1 resize=button3

dkcmd set border width=$border_width colour focus='#0087CA' unfocus='#767676' urgent='#ee5555'

# Rules

dkcmd rule class="^Brave-browser$" ws=2
} >> "$logfile" 2>&1 # append responses

if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "dkrc has errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"; print}' "$logfile")"
	exit 1
fi
exit 0
