#!/bin/bash

popup_powermenu() {
    eww open powermenu --toggle
}

popup_sysmenu() {
    eww open sysinfo --toggle
}

case "$1" in
    powermenu ) popup_powermenu;;
    sysmenu) popup_sysmenu ;;
    *)
        echo "Unkown action"
        exit 1
        ;;
esac
