#!/bin/bash

# Function to switch layouts
switch_layout() {
  # Get all layouts for all workspaces
  layouts=$(dkcmd status type=full num=1 | awk '/^workspaces:/ {sub(/^workspaces: /, ""); gsub(/(*)?[0-9]*:\w*:/, ""); print}')

  # Make layout an array
  IFS=' ' read -r -a layout_array <<< "$layouts"

  # Get the current workspace
  ws=$(xdotool get_desktop)

  # Increment workspace by one to fix 0 indexing
  ((cur_ws = ws + 1))

  # Get current layout based on the current workspace
  curr_layout=${layout_array[$ws]}

  layout_list=("grid" "mono" "tile" "dwindle" "none")

  case "$curr_layout" in
    "grid")   current_index=0 ;;
    "mono")   current_index=1 ;;
    "tile")   current_index=2 ;;
    "dwindle") current_index=3 ;;
    "none")   current_index=4 ;;
    *)        echo "Current layout not found in the layout list." ;;
  esac

  # Calculate the index of the next layout
  ((next_index = (current_index + 1) % ${#layout_list[@]}))

  # Get the next layout
  next_layout=${layout_list[next_index]}

  # Uncomment this line to apply the layout change
  dkcmd ws "$cur_ws" set layout "$next_layout"
}

# Call the function to switch layouts
switch_layout
