#!/bin/bash

get_strength() {
    strength=$(nmcli -t -f SIGNAL device show | grep -oP ':\K[0-9]+')
    echo "$strength"
}

symbol() {
    connected=$(nmcli device show | grep "GENERAL.STATE:.*100" > /dev/null && echo 1 || echo 0)
    strength=$(get_strength)

    if [ "$connected" -eq 1 ]; then
        if [ "$strength" -ge 75 ]; then
            echo "󰤥"
        elif [ "$strength" -ge 50 ]; then
            echo "󰤢"
        elif [ "$strength" -ge 25 ]; then
            echo "󰤟"
        else
            echo "󰤨"
        fi
    else
        echo "󰤮"
    fi
}

ssid() {
    name=$(nmcli -t -f NAME connection show --active | grep -v '^lo$')
    [ -z "$name" ] && echo "Disconnected" || echo "$name"
}

name() {
    name=$(nmcli -t -f NAME connection show --active | grep -v '^lo$')
    [ -z "$name" ] && echo "disconnected" || echo "connected"
}

status() {
    name=$(nmcli -t -f NAME connection show --active)
    [ -z "$name" ] && echo "Disconnected" || echo "Connected"
}

disconnect() {
    wifiname=$(nmcli -t -f NAME connection show --active)
    [ -n "$wifiname" ] && nmcli connection down "$wifiname"
}

connect() {
    iface=$(nmcli -t -f DEVICE device show --active)
    [ -n "$iface" ] && nmcli connection up ifname "$iface"
}

toggle() {
    name=$(nmcli -t -f NAME connection show --active)
    if [ -z "$name" ]; then
        connect
    else
        disconnect
    fi
}

case "$1" in
    icon) symbol ;;
    ssid) ssid ;;
    name|class) name ;;
    status) status ;;
    disconnect) disconnect ;;
    connect) connect ;;
    toggle) toggle ;;
    *) echo "Invalid argument" >&2
       exit 1
       ;;
esac
