#!/bin/bash

# Subscribe to pulseaudio sink changes  
pactl subscribe | rg --line-buffered "on sink" | while read -r _; do

    # Get human readable volume
    volume=$(pamixer --get-volume-human | tr -d '%')

    echo "$volume"
done
