#!/bin/bash

while :; do

# Get active window ID
active_window_id=$(xdotool getactivewindow)

# Extract WM_CLASS in one step
wm_class=$(xprop -id "$active_window_id" | grep "WM_CLASS(STRING)" | cut -d'"' -f2)

# Capitalize the first letter of each word in wm_class
wm_class=$(echo "$wm_class" | sed 's/\b\([a-z]\)/\u\1/g')

echo "$wm_class"
sleep 0.1
done
